[package]

name = "popongong"
version = "0.0.0"
authors = ["Jared <jared.shay@gmail.com>"]

[dependencies]
rand = "^0.5"

[dependencies.sdl2]
version = "0.31"
default-features = false
features = ["mixer"]
